#!/usr/bin/env python3
"""##CHRIS 2026-10-04 (Task Y2): generate the "A-fixed" arrays (261012 sec. 3) -- method A with the divider HELD for the
whole record -- and print their cost. Nothing is submitted. The existing generated files are not touched: this script only
READS the method-A task files and writes NEW files (tasks_AF_*, cells_Afix_*, conf_Afix_*, fetch_afix.sh).

Same cells, positions, seeds and stencil as method A, by construction: every line of tasks_A_<cell>.txt
    A <rel>/<cell>/x_<pos> <x_wall> <seed> <L0> <H> <Ns> 300000 600
becomes
    AF <REL_AF>/<cell>/x_<pos> <x_wall> <seed> <L0> <H> <Ns> 312000 1200 600
i.e. --wall-hold-steps = 12000 + 300000 (200 sigma-time equilibration + the 5000 sigma-time record, dt = 1/60 sigma-time)
and a released tail of --steps = 1200 (20 sigma-time; only so the trace, written after the release only, records the
temperatures). The output directory REL_AF is new; the method-A directories are never written.
The binary is unchanged (no build input changes): the same 279282b build that ran method B and method A.

Cost [INFERENCE]: an A-fixed trajectory runs the same number of steps as a method-A trajectory (+0.4 %), so its cost is
taken from Round 1: for the eta = 0.10 cells the measured wall time of the method-A array task (sacct, round1_timing_261003);
for the H = 40 cell and every pi/8 cell the measured-scaling rule of round1_timing_261003 (p* = the steepest local
exponent measured, 2.99; pi/8 from the method-A pilot, 20.5 s per wave of 16 at N_s = 50). --time = 3 x the prediction,
rounded up to 15 min, capped at 72 h; one array default (3 x the largest non-H40 cell) and one override line for H40.
usage (from hspist3/): python3 cluster/gen_afix_sbatch_261004.py
"""
import math, os, sys
HERE = os.path.dirname(os.path.abspath(__file__)); HS = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import round1_timing_261003 as RT
CONF = os.path.join(HERE, "confinement_20261013")
REL_A = "experiments_energy_transfer/paper1_confinement_A_20261013"
REL_AF = "experiments_energy_transfer/paper1_confinement_Afix_261004"
SCRATCH = "/mnt/lustre/koa/scratch/charing"
HOLD, POST, EVERY, CPUS = 312000, 1200, 600, 16
THR = {"Afix_0.10": 2, "Afix_0.39": 2, "Afix_pilot": 1}


def af_lines(cid, src_cell=None):
    out = []
    for l in open(os.path.join(CONF, f"tasks_A_{src_cell or cid}.txt")):
        f = l.split()
        assert f[0] == "A" and f[7] == "300000" and f[8] == "600", l
        pos = os.path.basename(f[1])
        out.append(f"AF {REL_AF}/{cid}/{pos} {f[2]} {f[3]} {f[4]} {f[5]} {f[6]} {HOLD} {POST} {EVERY}")
    return out


def pstar():
    loc = []
    for g in RT.SACCT:
        hs = [c for c in RT.cells(g) if "_H_H" in c]
        pw = {RT.ns(g, c): RT.sec(el) / math.ceil(RT.ntraj(g, c) / RT.sbatch(g)[0])
              for c in hs for t, el, st in RT.SACCT[g] if st == "C" and RT.cells(g)[t - 1] == c}
        n = sorted(pw); loc.append(math.log(pw[n[-1]] / pw[n[-2]]) / math.log(n[-1] / n[-2]))
    return max(loc)


def predict_h(group, cid, n, Ns):
    """Wall hours of one A-fixed cell (n trajectories, 16 at a time)."""
    waves = math.ceil(n / CPUS)
    if group == "Afix_0.10":
        cl = RT.cells("A_0.10"); t = cl.index(cid) + 1
        el, st = [(e, s) for tt, e, s in RT.SACCT["A_0.10"] if tt == t][0]
        if st == "C":
            return RT.sec(el) / 3600, "Round 1 sacct (measured)"
        ref = [c for c in cl if "_H_H20" in c][0]; tr = cl.index(ref) + 1
        pw = RT.sec([e for tt, e, s in RT.SACCT["A_0.10"] if tt == tr][0]) / math.ceil(RT.ntraj("A_0.10", ref) / CPUS)
        return pw * (Ns / RT.ns("A_0.10", ref)) ** P * waves / 3600, f"H20 per wave x 2^{P:.2f}"
    pw50 = RT.PILOT_ELAPSED_S / math.ceil(RT.PILOT_N / RT.PILOT_P)
    return pw50 * max(1.0, Ns / 50) ** P * waves / 3600, f"pilot per wave x (N_s/50)^{P:.2f}"


def hms(h):
    m = max(30, math.ceil(min(72.0, h) * 4) * 15)
    return f"{m // 60}:{m % 60:02d}:00" if m < 1440 else f"{m // 1440}-{(m % 1440) // 60:02d}:{m % 60:02d}:00"


def sbatch_text(g, ncell, part, tstr):
    return f"""#!/bin/bash
# ##CHRIS 2026-10-04 (Task Y2): Paper 1 confinement campaign, "A-fixed" (261012 sec. 3): method A with the divider HELD for
# the whole record (--wall-hold-steps=312000, --steps=1200), group {g}. Generated by cluster/gen_afix_sbatch_261004.py from
# the method-A task files (same cells, positions, seeds). NOT LAUNCHED. Output: $HD_DATA/{REL_AF}/ (new; method-A dirs untouched).
# One array task = one cell (cells_{g}.tsv line N); the cell's trajectories run {CPUS} at a time.
# Partition {part}, account uh, scratch {SCRATCH} (files DELETED 90 days after last write).
# Submit from ~/harddisks/hspist3 after `mkdir -p logs`; the binary must be the recorded build (logs/BUILD_KOA_LAST.hash).
#   sbatch --array=1-{ncell}%{THR[g]} cluster/confinement_20261013/conf_{g}.sbatch      (runsheet step 9 for --time overrides)
#SBATCH --job-name=conf-{g}
#SBATCH --partition={part}
#SBATCH --account=uh
#SBATCH --time={tstr}
#SBATCH --cpus-per-task={CPUS}
#SBATCH --mem=8G
#SBATCH --output=logs/%x_%A_%a.out
#SBATCH --error=logs/%x_%A_%a.out
set -uo pipefail
SCRATCH="{SCRATCH}"
cd "$SLURM_SUBMIT_DIR"                       # hspist3/ (source, scripts, the koa-built binary)
source cluster/koa_env.sh || exit 1
export HD_BIN="$PWD/00ALLINONE" HD_DATA="$SCRATCH/harddisks/hspist3"
gcc --version | head -1; "$HD_BIN" --version | head -2
[ -s logs/BUILD_KOA_LAST.hash ] || {{ echo "STOP: no logs/BUILD_KOA_LAST.hash -- build with cluster/build_koa.sh first"; exit 1; }}
sha256sum --status -c logs/BUILD_KOA_LAST.hash || {{ echo "STOP: ./00ALLINONE is not the build recorded in logs/BUILD_KOA_LAST.hash"; exit 1; }}
export HD_BUILD="$("$HD_BIN" --version | head -1)"
echo "$HD_BUILD" | grep -Eq -- "git [0-9a-f]+  target koa" || {{ echo "STOP: not a clean koa build: $HD_BUILD"; exit 1; }}
CELL=$(sed -n "${{SLURM_ARRAY_TASK_ID}}p" cluster/confinement_20261013/cells_{g}.tsv)
TASKS=cluster/confinement_20261013/tasks_AF_$CELL.txt
echo "cell $CELL: $(wc -l < "$TASKS") trajectories, {CPUS} in parallel"
xargs -P {CPUS} -L 1 bash cluster/confinement_20261013/conf_worker.sh < "$TASKS"
echo "A-fixed: per-seed red_<seed>.csv written by the worker (reduce_AF.py, held window [200, 5200))"
echo "cell $CELL done; failures: $(grep -c FAILED logs/conf-{g}_${{SLURM_ARRAY_JOB_ID}}_${{SLURM_ARRAY_TASK_ID}}.out || true)"
"""


def main():
    global P
    P = pstar()
    print(f"### A-fixed arrays (261012 sec. 3): tasks from the method-A task files, hold {HOLD} steps, tail {POST}, every {EVERY}\n")
    print("| group | task | cell | N_s | trajectories | same (position, seed) set as method A | predicted wall (h) | basis | core-h (wall x 16) |")
    print("|---|---|---|---|---|---|---|---|---|")
    lines_out, tot = [], {}
    for lab in ("0.10", "0.39"):
        g = f"Afix_{lab}"; cl = open(os.path.join(CONF, f"cells_A_{lab}.tsv")).read().split()
        preds = []
        for t, cid in enumerate(cl, 1):
            L = af_lines(cid)
            A = [l.split() for l in open(os.path.join(CONF, f"tasks_A_{cid}.txt"))]
            same = sorted((os.path.basename(a[1]), a[3]) for a in A) == sorted((l.split()[1].rsplit("/", 1)[1], l.split()[3]) for l in L)
            open(os.path.join(CONF, f"tasks_AF_{cid}.txt"), "w").write("\n".join(L) + "\n")
            Ns = int(A[0][6]); h, basis = predict_h(g, cid, len(L), Ns); preds.append((t, cid, h))
            tot[g] = tot.get(g, 0.0) + h * CPUS
            print(f"| {g} | {t} | {cid} | {Ns} | {len(L)} | {'yes' if same else '**NO**'} | {h:.2f} | {basis} | {h * CPUS:.1f} |")
        open(os.path.join(CONF, f"cells_{g}.tsv"), "w").write("\n".join(cl) + "\n")
        big = [p for p in preds if "_H_H40" in p[1]][0]
        default = hms(3 * max(h for t, c, h in preds if t != big[0]))
        open(os.path.join(CONF, f"conf_{g}.sbatch"), "w").write(sbatch_text(g, len(cl), "shared", default))
        rest = ",".join(str(t) for t, c, h in preds if t != big[0])
        lines_out += [f"sbatch --array={big[0]} --time={hms(3 * big[2])} cluster/confinement_20261013/conf_{g}.sbatch",
                      f"sbatch --array={rest}%{THR[g]} cluster/confinement_20261013/conf_{g}.sbatch"]
        print(f"| {g} | -- | sbatch default --time = 3 x the largest non-H40 cell = {default}; H40 override {hms(3 * big[2])} | | | | | | |")
    # the A-fixed pilot: the method-A pilot's 20 tasks (pi/8 anchor, seeds 9700-9703), held
    L = af_lines("pilot_epi8_H_H10_L10")
    open(os.path.join(CONF, "tasks_AF_pilot_epi8_H_H10_L10.txt"), "w").write("\n".join(L) + "\n")
    open(os.path.join(CONF, "cells_Afix_pilot.tsv"), "w").write("pilot_epi8_H_H10_L10\n")
    open(os.path.join(CONF, "conf_Afix_pilot.sbatch"), "w").write(sbatch_text("Afix_pilot", 1, "sandbox", "1:00:00"))
    print(f"\nA-fixed pilot: {len(L)} trajectories (the method-A pilot's tasks, held), sandbox, 1:00:00")
    print(f"\ntotal (upper bound, wall x 16 cores): Afix_0.10 {tot['Afix_0.10']:.1f} core-h, Afix_0.39 {tot['Afix_0.39']:.1f} core-h, "
          f"together {sum(tot.values()):.1f} core-h; p* = {P:.2f}")
    print("\nsubmission lines (runsheet step 9; at most 64 cores: 2 x 16 + 2 x 16):\n")
    print("    sbatch --array=1-1 cluster/confinement_20261013/conf_Afix_pilot.sbatch      (first, sandbox; gate G1)")
    for l in lines_out: print("    " + l)
    fetch = f"""#!/usr/bin/env bash
# ##CHRIS 2026-10-04 (Task Y2): copy the A-fixed campaign back FROM KOA (run on the Mac, from the repo root). Summaries of every
# cell, plus the full A-fixed pilot cell (its event logs feed gate G1). Nothing on either side is deleted.
KOA_USER=charing; SCRATCH="{SCRATCH}"; DTN=$KOA_USER@koa-dtn.its.hawaii.edu; R=$SCRATCH/harddisks/hspist3
case "${{1:-all}}" in
  pilot) rsync -av "$DTN:$R/{REL_AF}/pilot_epi8_H_H10_L10/" "hspist3/{REL_AF}/pilot_epi8_H_H10_L10/" ;;
  *) rsync -av --prune-empty-dirs --include='*/' --include='red_*.csv' --include='run_*.log' --include='summary_*.csv' \\
           --exclude='*' "$DTN:$R/{REL_AF}/" "hspist3/{REL_AF}/" ;;
esac
"""
    open(os.path.join(CONF, "fetch_afix.sh"), "w").write(fetch)
    print("\nfiles written: tasks_AF_*.txt (19 cells + pilot), cells_Afix_{0.10,0.39,pilot}.tsv, conf_Afix_{0.10,0.39,pilot}.sbatch, "
          "fetch_afix.sh")


if __name__ == "__main__":
    main()
